apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  name: certificaterequests.cert-manager.io
spec:
  conversion:
    strategy: Webhook
    webhookClientConfig:
      service:
        namespace: "example"
        name: 'cert-manager-webhook'
        path: /convert
---
apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  name: certificates.cert-manager.io
spec:
  conversion:
    strategy: Webhook
    webhookClientConfig:
      service:
        namespace: "example"
        name: 'cert-manager-webhook'
        path: /convert
---
apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  name: challenges.acme.cert-manager.io
spec:
  conversion:
    strategy: Webhook
    webhookClientConfig:
      service:
        namespace: kube-system
        name: 'cert-manager-webhook'
        path: /convert
---
apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  name: clusterissuers.cert-manager.io
spec:
  conversion:
    strategy: Webhook
    webhookClientConfig:
      service:
        namespace: kube-system
        name: 'cert-manager-webhook'
        path: /convert
---
apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  name: issuers.cert-manager.io
spec:
  conversion:
    strategy: Webhook
    webhookClientConfig:
      service:
        namespace: kube-system
        name: 'cert-manager-webhook'
        path: /convert
---
apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  name: orders.acme.cert-manager.io
spec:
  conversion:
    strategy: Webhook
    webhookClientConfig:
      service:
        namespace: kube-system
        name: 'cert-manager-webhook'
        path: /convert
