apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
bases:
  - ../cluster
  - ../namespaced
resources:
  - cert-manager-clusterrolebinding.yaml
  - cert-manager-rolebinding.yaml
patchesStrategicMerge:
  - cert-manager-crd-patch.yaml
  - cert-manager-webhook-patch.yaml
