apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - upstream-cert-manager.yaml
  - aws-pca-issuer
patchesStrategicMerge:
  - patches/cainjector-deployment-resources-patch.yaml
  - patches/cert-manager-deployment-flags-ns-patch.yaml
  - patches/cert-manager-deployment-resource-patch.yaml
  - patches/clusterrolebinding-ns-patch.yaml
  - patches/delete-cert-manager-ns-patch.yaml
  - patches/rolebinding-ns-patch.yaml
  - patches/webhook-deployment-resource-patch.yaml
  - patches/webhook-ns-patch.yaml
