apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - cert-manager-cainjector.yaml
  - cert-manager-webhook.yaml
  - cert-manager.yaml
  - rbac.yaml
patchesStrategicMerge:
  - cert-manager-patch.yaml
